### ISSUE TITLE
Add functions for relative dates

### ISSUE THREAD

**Issue by DevL** [magplus/good_times#10]
Unsure about the utility, but an idea could be to add expressive functions such as `tomorrow` as an alternative to `a_day_from_now` and `yesterday` as an alternative to `a_day_ago`.

**Comment by martinsvalin** [comment]
Oh definitely. Naming is important. What is the best way to alias a function? Ideally they'd have the same `@doc`, right? [Stackoverflow](http://stackoverflow.com/questions/28280267/can-i-have-an-alias-of-function-inside-the-same-library-in-elixir) suggests `defdelegate`, but that defines a new function that calls the original, and would need its own `@doc`.

**Comment by DevL** [comment]
Since `@doc` and `@spec` are set on a per function basis, I _think_ one simply skips setting them when declaring the "alias".

Something like this:

```elixir
@doc "some doc"
@spec original_function(integer) :: integer
def original_function(x), do: x * 2

def alias_to_original_function(x), do: original_function(x) 
```

I believe the second function will have the same documentation and spec. One could either state in the docstring that `alias_to_original_function` exists and behaves the same, or one could set a new `@doc`.

**Comment by martinsvalin** [comment]
No, the second function doesn't inherit documentation (or spec, I assume).

```
defmodule A do
  @doc "hi"
  def foo, do: IO.puts "foo"
  def bar, do: foo
end
```

```
iex> h A.foo
  def foo()
hi

iex> h A.bar
  def bar()
```

The directives are on a per-function-basis, but you're defining a new function with your `alias_to_original_function`. This is the same as with `defdelegate`.

**Comment by DevL** [comment]
Alright. I was thinking the latest defined module attribute would be applied, but in hindsight that doesn't make sense as then you could set the docstring for the first function in a module and all other functions would "inherit" it.

How about "copying" the docstring then?

```elixir
docs = "some docs"
@doc docs
def doubler(x), do: x * 2

@doc docs
def alias_to_doubler(x), do: doubler(x)
```

Typespecs would probably have to be duplicated.

**Comment by DevL** [comment]
To clarify, I don't think there's any other notion of an alias in Elixir/Erlang than creating a new function that invokes the original function.

**Comment by martinsvalin** [comment]
So, from the discussion in #28, we should let `yesterday`, `tomorrow` and `today` return plain `date`s, not be aliases for `a_day_ago`, `a_day_from_now`, `now`?

**Comment by DevL** [comment]
Yes, I think that makes sense. A `GoodTimes.date` module perhaps?

**Comment by DevL** [comment]
Or should we roll it into the core module?
