### ISSUE TITLE
Add type conversion functions

### ISSUE THREAD

**Issue by DevL** [magplus/good_times#12]
So far, GoodTimes only work with datetimes. Do we want to add convenience conversion functions that, given a datetime, returns e.g. only the date portion?

```elixir
now   # {{2015, 3, 2}, {23, 06, 54}}
|> to_date  # {2015, 3, 2}
```

The conversion functions could pattern match on a number of possible inputs and convert them into e.g. a date. A datetime to date would dump the time portion. A date to date would return it unchanged. A time to date could be considered bad data and fail or return `{0, 1, 1}` if that makes any sense at all.

Makes this sense to be a part of this library or are such conversin functions simply out of the scope?

Ping @martinsvalin

**Comment by martinsvalin** [comment]
_If_ we do this, we'll be moving from one module to multiple modules. I don't want to mix conversion functions and datetime arithmetic in the same module. Something like `GoodTimes.Conversion` and `GoodTimes.Arithmetic`, but it's a bummer to move to boring module naming.

Anyway, that would make this a backwards-incompatible change. You'd `import GoodTimes.Arithmetic` (or whatever) instead of just GoodTimes for the functionality we have today.

I'm not entirely sure about scope yet.

**Comment by DevL** [comment]
We can punt on the decision, but we could easily break out any conversion functions into a separate library. Removing this from 1.0 for now.

**Comment by DevL** [comment]
A `GoodTimes.Convert` module would have non-imported functions read rather nicely I think.

E.g. `now |> GoodTimes.Convert.to_date` and `{2015, 1, 12} |> GoodTimes.Convert.to_datetime`. The one ambiguity to deal with is how to handle `date`s and `time`s being converted to a `datetime`. Since both are three-element tuples, and there's an overlap of possible, valid values, it can devolve into guessing. For that reason, it makes sense to have very explicit function names, e.g. `time_to_datetime`, `date_to_datetime`. For consistency, it probably makes sense to do the same for functions that convert to a `datetime`, i.e. `time_to_datetime` and `date_to_datetime`.

A rough draft of functions to add.

```
time_to_datetime/1
date_to_datetime/1
datetime_to_date/1 # possibly just to_date/1
datetime_to_time/1 # possibly just to_time/1
```

**Comment by martinsvalin** [comment]
If `to_datetime/1` assumes `{h, m, s} when h < 24` means it's a `time`, else it's a `date`, I'd be fine with it. As long as it's properly documented, of course. I don't expect a lot of New Testament scholars would want convenience functions for converting dates. They're on their own.

**Comment by DevL** [comment]
Expressiveness be damned, the code becomes trivial one-liners if the function names are completely explicit and there are no surprises lurking anywhere. :)

**Comment by martinsvalin** [comment]
ok
