### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by DevL** [magplus/good_times#35]
### Before release
* [x] Review all module docs
* [x] Convert as many tests as possible to doctests
* [x] Generate and review documentation
* [x] Write blog post (Lennart)
* [x] Bump version in `mix.exs`
* [x] Bump version in `good_times.ex`
* [x] Bump version in Readme example for installing the Hex package.
* [x] Flesh out examples in the Readme.
* [x] Add cheeky citations to the Readme. :)

### At release
* [x] Release on Github (tag as v1.0.0 and name the release v1.0.0), listing all the added modules and their functions in the release note.
* [x] Build and publish Hex package.
* [x] Build and upload Hex docs.
* [x] Tweet about it.
* [x] Announce it on the elixir-lang-talk mailing list.
* [ ] Celebrate (important!).

**Comment by DevL** [comment]
Just need to sort out some DNS (am moving the blog to Ghost) before publishing the blog post.

**Comment by DevL** [comment]
@martinsvalin Just one more thing left before we can close this issue. :grinning:

**Comment by martinsvalin** [comment]
:celebration:

**Comment by DevL** [comment]
Breaking out the celebratory bit due ot closing this repo.
