### ISSUE TITLE
Add expressive time functions

### ISSUE THREAD

**Issue by DevL** [magplus/good_times#37]
Similar to `GoodTimes.Date`'s `today`, add a `GoodTimes.Time` module that holds functions such as `noon` and `midnight`. This enables expressions such as `tomorrow |> at noon`.

Future additions can be `beer_o_clock` and `1337`. 😝

**Comment by martinsvalin** [comment]
Would you use them over explicitly stating `{0, 0, 0}` or `{12, 0, 0}`? I probably wouldn't. The time tuple is readable as it is, imho.

**Comment by DevL** [comment]
Feature creep? You're most likely right.
