### ISSUE TITLE
Add parse function to GoodTimes.Convert

### ISSUE THREAD

**Issue by DevL** [magplus/good_times#41]
The scope of the input that the parse function should handle is up for debate.

At a minimum it should handle the following:

```elixir
"2015-03-23 08:32:45"
"2015-3-23 8:32:45"
"2015-03-23"
"2015-3-23"
```

#39 and #40 can be reimplemented using this parse function.

**Comment by DevL** [comment]
If we're to implement ISO 8601 support we also should support the following:

> A single point in time can be represented by concatenating a complete date expression, the letter T as a delimiter, and a valid time expression. For example "2007-04-05T14:30".
>
> If a time zone designator is required, it follows the combined date and time. For example "2007-04- 05T14:30Z" or "2007-04-05T12:30-02:00".

> Either basic or extended formats may be used, but both date and time must use the same format. The date expression may be calendar, week, or ordinal, and must use a complete representation. The time expression may use reduced accuracy. It is permitted to omit the 'T' character by mutual agreement.

This gives us a few more examples such as:

```elixir
"2015-03-24T08:26:45"
"2015-03-24T08:26:45Z"
"2015-03-24T09:26:45+01:00"
```
Then we have _basic_ vs _extended_ formats. But I guess we can start with a subset of ISO 8601 as long as we detail what's supported and what isn't.

**Comment by martinsvalin** [comment]
I agree that we should stick to ISO 8601. Let this be an explicitly documented scope for the date parsing. And while the parsing is incomplete, we document what subsets are implemented, and what formats are still unsupported.

It'd be great to sketch out a complete list of formats we can check off:

- [x] "2015-03-23 08:32:45"
- [x] "2015-3-23 8:32:45"
- [x] "2015-03-23"
- [x] "2015-3-23"
- [ ] Etc…

Preferably in the PR description, not a comment, though.
