### ISSUE TITLE
Add functions for decades, centuries, and millennia

### ISSUE THREAD

**Issue by DevL** [magplus/good_times#9]
Add similar convenience functions to deal with decades, centuries, and millennia.

## Examples

```Elixir
a_decade_ago # => {{2005, 3, 4}, {16, 48, 35}}
3 |> centuries_from_now # => {{2315, 3, 4}, {16, 48, 35}}
a_millennia_from_now # => {{3015, 3, 4}, {16,48,35}}
40 |> millennia_from {{0, 0, 0}, {0, 0, 0}} # => {{40000, 0, 0}, {0, 0, 0}}
```

**Comment by DevL** [comment]
These I'm quite uncertain of the utility of. `4 |> centuries_ago` compared to `400 |> years_ago` might be a bit redundant. This might be a good time to determine what we perceive the scope of this library to be.

Ping @martinsvalin

**Comment by martinsvalin** [comment]
I vote no on these. If we had a macro that defined our functions for us, we could make that public so people could create their own `a_fortnight_from_now` or `an_epoch_ago #=> {{1970, 1, 1}, {0, 0, 0}}`.

**Comment by DevL** [comment]
Then we're in agreement. Closing this issue.
